@startuml

skinparam backgroundColor #white
namespace PHP {
  class lzf << (E,#FF7700) Extension >> {
    +lzf_compress(string : string)
    +lzf_decompress(string : string)
    +lzf_optimized_for()
  }
  class yaml << (E,#FF7700) Extension >> {
    +{static} YAML_ANY_SCALAR_STYLE : int = 0 {readOnly}
    +{static} YAML_PLAIN_SCALAR_STYLE : int = 1 {readOnly}
    +{static} YAML_SINGLE_QUOTED_SCALAR_STYLE : int = 2 {readOnly}
    +{static} YAML_DOUBLE_QUOTED_SCALAR_STYLE : int = 3 {readOnly}
    +{static} YAML_LITERAL_SCALAR_STYLE : int = 4 {readOnly}
    +{static} YAML_FOLDED_SCALAR_STYLE : int = 5 {readOnly}
    +{static} YAML_NULL_TAG : string = "tag\:yaml\.org\,2002\:null" {readOnly}
    +{static} YAML_BOOL_TAG : string = "tag\:yaml\.org\,2002\:bool" {readOnly}
    +{static} YAML_STR_TAG : string = "tag\:yaml\.org\,2002\:str" {readOnly}
    +{static} YAML_INT_TAG : string = "tag\:yaml\.org\,2002\:int" {readOnly}
    +{static} YAML_FLOAT_TAG : string = "tag\:yaml\.org\,2002\:float" {readOnly}
    +{static} YAML_TIMESTAMP_TAG : string = "tag\:yaml\.org\,2002\:timestamp" {readOnly}
    +{static} YAML_SEQ_TAG : string = "tag\:yaml\.org\,2002\:seq" {readOnly}
    +{static} YAML_MAP_TAG : string = "tag\:yaml\.org\,2002\:map" {readOnly}
    +{static} YAML_PHP_TAG : string = "\!php\/object" {readOnly}
    +{static} YAML_MERGE_TAG : string = "tag\:yaml\.org\,2002\:merge" {readOnly}
    +{static} YAML_BINARY_TAG : string = "tag\:yaml\.org\,2002\:binary" {readOnly}
    +{static} YAML_ANY_ENCODING : int = 0 {readOnly}
    +{static} YAML_UTF8_ENCODING : int = 1 {readOnly}
    +{static} YAML_UTF16LE_ENCODING : int = 2 {readOnly}
    +{static} YAML_UTF16BE_ENCODING : int = 3 {readOnly}
    +{static} YAML_ANY_BREAK : int = 0 {readOnly}
    +{static} YAML_CR_BREAK : int = 1 {readOnly}
    +{static} YAML_LN_BREAK : int = 2 {readOnly}
    +{static} YAML_CRLN_BREAK : int = 3 {readOnly}

    +yaml_parse(input, pos = «unknown», inout ndocs = «unknown», callbacks : array = «unknown»)
    +yaml_parse_file(filename, pos = «unknown», inout ndocs = «unknown», callbacks : array = «unknown»)
    +yaml_parse_url(url, pos = «unknown», inout ndocs = «unknown», callbacks : array = «unknown»)
    +yaml_emit(data, encoding = «unknown», linebreak = «unknown», callbacks : array = «unknown»)
    +yaml_emit_file(filename, data, encoding = «unknown», linebreak = «unknown», callbacks : array = «unknown»)
  }
}
@enduml
